//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGlobalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPGlobalization.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data series.
        /// </summary>
        internal static string AddDataSeries {
            get {
                return ResourceManager.GetString("AddDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        internal static string Arial {
            get {
                return ResourceManager.GetString("Arial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓.
        /// </summary>
        internal static string ArrowDown {
            get {
                return ResourceManager.GetString("ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        internal static string ArrowUp {
            get {
                return ResourceManager.GetString("ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenir.
        /// </summary>
        internal static string Avenir {
            get {
                return ResourceManager.GetString("Avenir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis configuration.
        /// </summary>
        internal static string AxisConfiguration {
            get {
                return ResourceManager.GetString("AxisConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis font size (X/Y).
        /// </summary>
        internal static string AxisFontSize {
            get {
                return ResourceManager.GetString("AxisFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis labels style (X/Y).
        /// </summary>
        internal static string AxisLabelsStyle {
            get {
                return ResourceManager.GetString("AxisLabelsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back color.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue scale.
        /// </summary>
        internal static string BlueScale {
            get {
                return ResourceManager.GetString("BlueScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue to red.
        /// </summary>
        internal static string BlueToRed {
            get {
                return ResourceManager.GetString("BlueToRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodoni.
        /// </summary>
        internal static string Bodoni {
            get {
                return ResourceManager.GetString("Bodoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart box.
        /// </summary>
        internal static string ChartBox {
            get {
                return ResourceManager.GetString("ChartBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart size [px] (width/height).
        /// </summary>
        internal static string ChartSize {
            get {
                return ResourceManager.GetString("ChartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart title.
        /// </summary>
        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color template.
        /// </summary>
        internal static string ColorTemplate {
            get {
                return ResourceManager.GetString("ColorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolas.
        /// </summary>
        internal static string Consolas {
            get {
                return ResourceManager.GetString("Consolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color.
        /// </summary>
        internal static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data series.
        /// </summary>
        internal static string DataSeries {
            get {
                return ResourceManager.GetString("DataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font name.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style.
        /// </summary>
        internal static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franklin Gothic.
        /// </summary>
        internal static string FranklinGothic {
            get {
                return ResourceManager.GetString("FranklinGothic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frutiger.
        /// </summary>
        internal static string Frutiger {
            get {
                return ResourceManager.GetString("Frutiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futura.
        /// </summary>
        internal static string Futura {
            get {
                return ResourceManager.GetString("Futura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garamond.
        /// </summary>
        internal static string Garamond {
            get {
                return ResourceManager.GetString("Garamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray scale.
        /// </summary>
        internal static string GrayScale {
            get {
                return ResourceManager.GetString("GrayScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green scale.
        /// </summary>
        internal static string GreenScale {
            get {
                return ResourceManager.GetString("GreenScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green to red.
        /// </summary>
        internal static string GreenToRed {
            get {
                return ResourceManager.GetString("GreenToRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid lines.
        /// </summary>
        internal static string GridLines {
            get {
                return ResourceManager.GetString("GridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid lines color.
        /// </summary>
        internal static string GridLinesColor {
            get {
                return ResourceManager.GetString("GridLinesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helvetica.
        /// </summary>
        internal static string Helvetica {
            get {
                return ResourceManager.GetString("Helvetica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend font size.
        /// </summary>
        internal static string LegendFontSize {
            get {
                return ResourceManager.GetString("LegendFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend position.
        /// </summary>
        internal static string LegendPosition {
            get {
                return ResourceManager.GetString("LegendPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic scale.
        /// </summary>
        internal static string LogarithmicScale {
            get {
                return ResourceManager.GetString("LogarithmicScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major grid lines.
        /// </summary>
        internal static string MajorGridLines {
            get {
                return ResourceManager.GetString("MajorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major step (X/Y).
        /// </summary>
        internal static string MajorStep {
            get {
                return ResourceManager.GetString("MajorStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor grid lines.
        /// </summary>
        internal static string MinorGridLines {
            get {
                return ResourceManager.GetString("MinorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor step (X/Y).
        /// </summary>
        internal static string MinorStep {
            get {
                return ResourceManager.GetString("MinorStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (orig.).
        /// </summary>
        internal static string OriginalX {
            get {
                return ResourceManager.GetString("OriginalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y (orig.).
        /// </summary>
        internal static string OriginalY {
            get {
                return ResourceManager.GetString("OriginalY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        internal static string Rainbow {
            get {
                return ResourceManager.GetString("Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red scale.
        /// </summary>
        internal static string RedScale {
            get {
                return ResourceManager.GetString("RedScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red to blue.
        /// </summary>
        internal static string RedToBlue {
            get {
                return ResourceManager.GetString("RedToBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red to green.
        /// </summary>
        internal static string RedToGreen {
            get {
                return ResourceManager.GetString("RedToGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove data series.
        /// </summary>
        internal static string RemoveDataSeries {
            get {
                return ResourceManager.GetString("RemoveDataSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        internal static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rockwell.
        /// </summary>
        internal static string Rockwell {
            get {
                return ResourceManager.GetString("Rockwell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (scaled).
        /// </summary>
        internal static string ScaledX {
            get {
                return ResourceManager.GetString("ScaledX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y (scaled).
        /// </summary>
        internal static string ScaledY {
            get {
                return ResourceManager.GetString("ScaledY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        internal static string Scientific {
            get {
                return ResourceManager.GetString("Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend.
        /// </summary>
        internal static string ShowLegend {
            get {
                return ResourceManager.GetString("ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silicon steel.
        /// </summary>
        internal static string SiliconSteel {
            get {
                return ResourceManager.GetString("SiliconSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick.
        /// </summary>
        internal static string Thick {
            get {
                return ResourceManager.GetString("Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times New Roman.
        /// </summary>
        internal static string TimesNewRoman {
            get {
                return ResourceManager.GetString("TimesNewRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title font size.
        /// </summary>
        internal static string TitleFontSize {
            get {
                return ResourceManager.GetString("TitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univers.
        /// </summary>
        internal static string Univers {
            get {
                return ResourceManager.GetString("Univers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Verdana {
            get {
                return ResourceManager.GetString("Verdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis title.
        /// </summary>
        internal static string XAxisTitle {
            get {
                return ResourceManager.GetString("XAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X axis limits (min./max.).
        /// </summary>
        internal static string XLimits {
            get {
                return ResourceManager.GetString("XLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X scale.
        /// </summary>
        internal static string XScale {
            get {
                return ResourceManager.GetString("XScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis title.
        /// </summary>
        internal static string YAxisTitle {
            get {
                return ResourceManager.GetString("YAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y axis limits (min./max.).
        /// </summary>
        internal static string YLimits {
            get {
                return ResourceManager.GetString("YLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y scale.
        /// </summary>
        internal static string YScale {
            get {
                return ResourceManager.GetString("YScale", resourceCulture);
            }
        }
    }
}
